//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.17 at 12:02:53 PM IST 
//


package approval.project.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customerid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="customername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customeraddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contact" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attempts" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="customeraadhaar" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="customerpan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="updatestatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customer", propOrder = {
    "customerid",
    "customername",
    "customeraddress",
    "customerstatus",
    "contact",
    "username",
    "password",
    "attempts",
    "customeraadhaar",
    "customerpan",
    "updatestatus"
})
public class Customer {

    protected int customerid;
    @XmlElement(required = true)
    protected String customername;
    @XmlElement(required = true)
    protected String customeraddress;
    @XmlElement(required = true)
    protected String customerstatus;
    protected long contact;
    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String password;
    protected int attempts;
    protected long customeraadhaar;
    @XmlElement(required = true)
    protected String customerpan;
    @XmlElement(required = true)
    protected String updatestatus;

    /**
     * Gets the value of the customerid property.
     * 
     */
    public int getCustomerid() {
        return customerid;
    }

    /**
     * Sets the value of the customerid property.
     * 
     */
    public void setCustomerid(int value) {
        this.customerid = value;
    }

    /**
     * Gets the value of the customername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * Sets the value of the customername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomername(String value) {
        this.customername = value;
    }

    /**
     * Gets the value of the customeraddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomeraddress() {
        return customeraddress;
    }

    /**
     * Sets the value of the customeraddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomeraddress(String value) {
        this.customeraddress = value;
    }

    /**
     * Gets the value of the customerstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerstatus() {
        return customerstatus;
    }

    /**
     * Sets the value of the customerstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerstatus(String value) {
        this.customerstatus = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     */
    public long getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     */
    public void setContact(long value) {
        this.contact = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the attempts property.
     * 
     */
    public int getAttempts() {
        return attempts;
    }

    /**
     * Sets the value of the attempts property.
     * 
     */
    public void setAttempts(int value) {
        this.attempts = value;
    }

    /**
     * Gets the value of the customeraadhaar property.
     * 
     */
    public long getCustomeraadhaar() {
        return customeraadhaar;
    }

    /**
     * Sets the value of the customeraadhaar property.
     * 
     */
    public void setCustomeraadhaar(long value) {
        this.customeraadhaar = value;
    }

    /**
     * Gets the value of the customerpan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerpan() {
        return customerpan;
    }

    /**
     * Sets the value of the customerpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerpan(String value) {
        this.customerpan = value;
    }

    /**
     * Gets the value of the updatestatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatestatus() {
        return updatestatus;
    }

    /**
     * Sets the value of the updatestatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatestatus(String value) {
        this.updatestatus = value;
    }

}
